# ============================================================
# POSTGRESQL - NEON
# ============================================================
#db.url=jdbc:postgresql://ep-restless-hall-aehwldwn-pooler.c-2.us-east-2.aws.neon.tech:5432/sysventas?sslmode=require
db.url=jdbc:sqlite:data/sysventas.db

# ============================================================
# DDL
# ============================================================
db.ddl.auto=false
db.ddl.script=schema_sv.sql